export interface Theme {
  /** Display name */
  name: string;
  /** Matches html[data-gct-theme="<slug>"] in src/themes/<slug>.css */
  slug: string;
}

export const themes: { light: Theme[]; dark: Theme[] } = {
  light: [
    { name: "Catppuccin Latte", slug: "catppuccin-latte" },
    { name: "Solarized Light", slug: "solarized-light" },
    { name: "Gruvbox Light", slug: "gruvbox-light" },
    { name: "Everforest Light", slug: "everforest-light" },
    { name: "One Light", slug: "one-light" },
    { name: "Ayu Light", slug: "ayu-light" },
    { name: "Rosé Pine Dawn", slug: "rose-pine-dawn" },
    { name: "Night Owl Light", slug: "night-owl-light" },
    { name: "Kanagawa Lotus", slug: "kanagawa-lotus" },
    { name: "Vitesse Light", slug: "vitesse-light" },
    { name: "Flexoki Light", slug: "flexoki-light" },
    { name: "Tomorrow", slug: "tomorrow" },
    { name: "PaperColor Light", slug: "papercolor-light" },
    { name: "Iceberg Light", slug: "iceberg-light" },
    { name: "Nord Light", slug: "nord-light" },
    { name: "Light+ (VS Code)", slug: "light-plus" },
    { name: "Quiet Light", slug: "quiet-light" },
    { name: "Selenized Light", slug: "selenized-light" },
    { name: "Gruvbox Material Light", slug: "gruvbox-material-light" },
    { name: "Tokyo Night Day", slug: "tokyo-night-day" },
    { name: "Sepia", slug: "sepia" },
  ],
  dark: [
    { name: "Dracula", slug: "dracula" },
    { name: "Catppuccin Mocha", slug: "catppuccin-mocha" },
    { name: "Catppuccin Macchiato", slug: "catppuccin-macchiato" },
    { name: "Catppuccin Frappé", slug: "catppuccin-frappe" },
    { name: "Nord", slug: "nord" },
    { name: "Gruvbox Dark", slug: "gruvbox-dark" },
    { name: "Tokyo Night", slug: "tokyo-night" },
    { name: "Tokyo Night Storm", slug: "tokyo-night-storm" },
    { name: "Monokai", slug: "monokai" },
    { name: "Solarized Dark", slug: "solarized-dark" },
    { name: "One Dark", slug: "one-dark" },
    { name: "Rosé Pine", slug: "rose-pine" },
    { name: "Rosé Pine Moon", slug: "rose-pine-moon" },
    { name: "Everforest Dark", slug: "everforest-dark" },
    { name: "Kanagawa", slug: "kanagawa" },
    { name: "Night Owl", slug: "night-owl" },
    { name: "Palenight", slug: "palenight" },
    { name: "Ayu Dark", slug: "ayu-dark" },
    { name: "Ayu Mirage", slug: "ayu-mirage" },
    { name: "Material Ocean", slug: "material-ocean" },
    { name: "Oceanic Next", slug: "oceanic-next" },
    { name: "Moonlight", slug: "moonlight" },
    { name: "Sonokai", slug: "sonokai" },
    { name: "Vitesse Dark", slug: "vitesse-dark" },
    { name: "Horizon", slug: "horizon" },
    { name: "Andromeda", slug: "andromeda" },
    { name: "Poimandres", slug: "poimandres" },
    { name: "Cobalt2", slug: "cobalt2" },
    { name: "Zenburn", slug: "zenburn" },
    { name: "Laserwave", slug: "laserwave" },
    { name: "Flexoki Dark", slug: "flexoki-dark" },
    { name: "Dark+ (VS Code)", slug: "dark-plus" },
    { name: "Monokai Pro", slug: "monokai-pro" },
    { name: "Gruvbox Material Dark", slug: "gruvbox-material-dark" },
    { name: "Nightfox", slug: "nightfox" },
    { name: "Iceberg", slug: "iceberg" },
    { name: "Tomorrow Night", slug: "tomorrow-night" },
    { name: "Snazzy", slug: "snazzy" },
    { name: "Panda", slug: "panda" },
    { name: "Aura", slug: "aura" },
    { name: "Everblush", slug: "everblush" },
    { name: "Challenger Deep", slug: "challenger-deep" },
    { name: "Synthwave '84", slug: "synthwave-84" },
  ],
};
